const express = require("express");
const { createproduct, getproductLis, singleproductsdeatils, updateroduct } = require("../controllers/porductController");
const multer = require("multer");
const { authMiddleware } = require("../middleware/aurthMiddleware");
const rolecheckmiddleware = require("../middleware/rolecheckmiddleware");
const route = express.Router();
const upload=multer();
route.post("/create",authMiddleware,rolecheckmiddleware("user"),upload.fields([{ name: 'thumbnail', maxCount: 1 }, { name: 'images', maxCount: 4 }]), createproduct);
route.get("/getproduct",getproductLis);
route.get("/prodcutdetails",singleproductsdeatils);
route.put("/update",upload.fields([{ name: 'thumbnail', maxCount: 1 }, { name: 'images', maxCount: 4 }]),updateroduct);
module.exports = route;
